[pyprland]
plugins = [
"expose",
"menubar",
"scratchpads",
"magnify",
"fetch_client_menu",
"toggle_special",
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm tmux new -s dropdown"
class = "kitty-dropterm"
size = "95% 93%"
lazy = true
excludes = ["wpp","volume","fm"]

[scratchpads.todo]
animation = "fromBottom"
command = "kitty --class kitty-todo taskwarrior-tui"
class = "kitty-todo"
size = "95% 93%"
lazy = true

[scratchpads.volume]
command = "pavucontrol"
animation = "fromTop"
class = "org.pulseaudio.pavucontrol"
size = "40% 90%"
lazy = true

[scratchpads.fm]
animation = "fromTop"
command = "kitty --class kitty-dropterm-fm yazi"
class = "kitty-dropterm-fm"
size = "75% 85%"
lazy = true

[scratchpads.wpp2]
animation = "fromTop"
command = "zapzap"
match_by = "class"
class = "com.rtosta.zapzap"
size = "80% 80%"
lazy = true

[scratchpads.spotify]
command = "spotify-launcher"
animation = "fromTop"
class = "Spotify"
unfocus = "hide"
size = "75% 80%"
lazy = true

[scratchpads.tuispotify]
animation = "fromTop"
command = "kitty --class spotify-tui ncspot"
class = "spotify-tui"
size = "75% 85%"
lazy = true

[scratchpads.mail]
command = "thunderbird"
animation = "fromTop"
class = "thunderbird"
size = "75% 80%"
lazy = true

[scratchpads.calendar]
command = "kitty --class kitty-dropterm-calendar calcurse"
animation = "fromTop"
class = "kitty-dropterm-calendar"
size = "75% 80%"
lazy = true

[scratchpads.calc]
command = "speedcrunch"
animation = "fromTop"
class = "org.speedcrunch.speedcrunch"
# title: SpeedCrunch
size = "75% 80%"
lazy = true

[scratchpads.gpt]
command = "noi-desktop"
animation = "fromBottom"
class = "Noi"
size = "80% 80%"
lazy = true

[scratchpads.obsidian]
command = "kitty --class kitty-obsidian nvim ~/Notes/obsidian/programming"
animation = "fromTop"
class = "kitty-obsidian"
size = "75% 80%"
lazy = true

[scratchpads.testing]
command = "/opt/insomnia/insomnia"
animation = "fromTop"
class = "Insomnia"
size = "85% 85%"
position = "8% 5%"
lazy = true

[scratchpads.yt_dlp_download]
animation = "fromTop"
command = "kitty --class yt_dlp_download ~/dev/scripts/downloader.sh"
class = "yt_dlp_download"
lazy = true
size = "65% 25%"

[menubar]
command = "waybar"

