[pyprland]
hyprland_version = "0.50.0"
plugins = [
"expose",
"menubar",
"scratchpads",
"magnify",
"fetch_client_menu",
"toggle_special",
]

[menubar]
command = "waybar"



[scratchpads.term]
animation = ""
command = "kitty --class kitty-dropterm tmux attach-session -t dropdown || tmux new -s dropdown"
class = "kitty-dropterm"
size = "95% 93%"
position = "2.5% 5%"
lazy = true

[scratchpads.todo]
animation = ""
command = "kitty --class kitty-todo taskwarrior-tui"
class = "kitty-todo"
size = "95% 93%"
position = "2.5% 5%"
pinned = false
lazy = true

[scratchpads.fm]
animation = ""
command = "kitty --class kitty-dropterm-fm yazi"
class = "kitty-dropterm-fm"
size = "75% 85%"
position = "15% 10%"
pinned = false
lazy = true

[scratchpads.tuispotify]
animation = ""
command = "kitty --class spotify-tui ncspot"
class = "spotify-tui"
size = "75% 85%"
position = "10% 10%"
pinned = false
lazy = true

[scratchpads.yt_dlp_download]
animation = ""
command = "kitty --class yt_dlp_download ~/dev/scripts/downloader.sh"
class = "yt_dlp_download"
lazy = true
size = "65% 25%"
position = "25% 5%"

[scratchpads.volume]
command = "pavucontrol"
animation = ""
class = "org.pulseaudio.pavucontrol"
size = "50% 70%"
position = "25% 15%"
pinned = false
lazy = true


[scratchpads.wpp2]
animation = ""
command = "zapzap"
match_by = "class"
class = "com.rtosta.zapzap"
size = "80% 80%"
position = "10% 10%"
lazy = true
pinned = false

[scratchpads.spotify]
command = "spotify-launcher"
animation = ""
class = "Spotify"
unfocus = "hide"
size = "80% 80%"
position = "10% 10%"
pinned = false
lazy = true


[scratchpads.mail]
command = "thunderbird"
animation = ""
class = "thunderbird"
size = "80% 80%"
position = "10% 10%"
pinned = false
lazy = true

[scratchpads.calc]
command = "speedcrunch"
animation = ""
class = "org.speedcrunch.speedcrunch"
# title: SpeedCrunch
size = "75% 80%"
position = "10% 10%"
lazy = true

[scratchpads.gpt]
command = "noi-desktop"
animation = ""
class = "Noi"
size = "80% 80%"
position = "10% 10%"
lazy = true
pinned = false

[scratchpads.testing]
command = "/usr/bin/bruno"
animation = ""
class = "bruno"
size = "85% 85%"
position = "8% 5%"
lazy = true
pinned = false

[scratchpads.auth]
animation = ""
command = "authenticator"
class = "com.belmoussaoui.Authenticator"
lazy = true
size = "45% 65%"
position = "10% 10%"
pinned = false

[scratchpads.secrets]
animation = ""
command = "bitwarden-desktop"
class = "Bitwarden"
lazy = true
size = "55% 65%"
pinned = false

